### ISSUE TITLE
Pass arg cloud in docker file

### ISSUE THREAD

**Issue by JincyChacko** [Linaro/openstack-exporter#6]
I am building uisng the image: quay.io/niedbalski/openstack-exporter:v0.0.6  in docker-compose file But getting an error "openstack-exporter: error: required argument 'cloud' not provided, try --help" .I trie dto pass arg cloud in docker-compose file using args: , it is not working and not supported.

**Comment by acidoxee** [comment]
I can't say if you are trying to build from source image, but if you are using the given base image, I think the following configuration should work:

```yml
version: '3.7'

services:
  openstack_exporter:
    image: quay.io/niedbalski/openstack-exporter:v0.0.7
    configs:
      - source: openstack_exporter
        target: /etc/openstack/clouds.yml
    command: ['default']

configs:
  openstack_exporter:
    external: true
```

I skipped a lot of stuff for brevity. The point here is the use of a custom `clouds.yml` file where you put all your configuration, [like indicated here](https://github.com/Linaro/openstack-exporter#openstack-configuration).

If you use that config, then I guess the cloud's name is `default`, hence the additional argument provided to the `command` key in the `openstack_exporter` service.
